site_name: Column Formatter
pages:
  - Home: 'index.md'
  - 'Setup & Configuration': 'setup.md'
  - 'Getting started': 'getting-started.md'
  - General:
    - 'Using the Editor': 'editor/index.md'
    - 'Properties': 'editor/properties.md'
    - 'Editing Code': 'editor/code-editor.md'
    - 'Save Options': 'editor/saving.md'
    - 'Sample Data': 'editor/sample-data.md'
    - 'Elements Tree': 'editor/tree.md'
  - Wizards:
    - 'Wizards': 'wizards/index.md'
    - '# Trending': 'wizards/number-trending.md'
    - 'Action Link': 'wizards/action-link.md'
    - 'Checkboxes': 'wizards/checkboxes.md'
    - 'Current User': 'wizards/current-user.md'
    - 'Data Bars': 'wizards/data-bars.md'
    - 'Donut': 'wizards/donut.md'
    - 'Mail To': 'wizards/mail-to.md'
    - 'Overdue': 'wizards/overdue.md'
    - 'Overdue Task': 'wizards/overdue-task.md'
    - 'Round Image': 'wizards/round-image.md'
    - 'Severity': 'wizards/severity.md'
    - 'Start Flow': 'wizards/start-flow.md'
    - 'Tiny Map': 'wizards/tiny-map.md'
    - 'Twitter Pic': 'wizards/twitter-pic.md'
  - About: 
    - 'About': 'about/index.md'
    - 'Localization': 'about/localization.md'
    - License: 'about/license.md'
theme:
  name: 'material'
  palette:
    primary: 'blue'
  logo: 'assets/sharepoint.png'
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: https://github.com/SharePoint/sp-dev-solutions
edit_uri: blob/master/docs/documentation/docs
